"""
config.py — Shared configuration for the city sensor simulation cluster.
Auto-generated by run.py. Pass flags to run.py to change these values.
"""

# ─── Redis ────────────────────────────────────────────────────────────────────
REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_DB   = 0

# ─── Simulation ───────────────────────────────────────────────────────────────
STEP_DELAY             = 0.01    # seconds between time-step publishes
NUM_SENSORS_PER_SERVER = 200
ZONE_A_START           = 1
ZONE_B_START           = 201

# ─── CORS ─────────────────────────────────────────────────────────────────────
# Change to ["http://localhost:5173"] for a production deployment.
CORS_ORIGINS = ["*"]
